logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.jdbc.datasource.init.ScriptUtils : DEBUG
    org.springframework.boot.autoconfigure: INFO

spring:
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/students_liquibase
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: springboot_dev
    password: dev

keycloak:
  realm: spring-boot-security-task
  #  without ssl using http instead of https
  auth-server-url: http://localhost:8442
  resource: spring-boot-security-task-client
  public-client: true
  bearer-only: true
