logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.jdbc.datasource.init.ScriptUtils : DEBUG
    org.springframework.boot.autoconfigure: DEBUG
spring:
  h2.console.enabled : true
  datasource.url : jdbc:h2:mem:testdb

keycloak:
  realm: spring-boot-security-task
  #  without ssl using http instead of https
  auth-server-url: http://localhost:8442
  resource: spring-boot-security-task-client
  public-client: true
  bearer-only: true

